#!/usr/bin/env bash


sysconf=0
devtools=0
dotfiles=0
vimplugins=0

help() {
    cat << EOF
usage: $0 [OPTIONS]

    --help          Show this message
    --all           Do every tasks

    --sysconf       System configuration
    --devtools      Install development tools
    --dotfiles      Copy dotfiles to home directory
    --vimplugins    Install vim plugins via vim-plug
EOF
}

for opt in "$@"; do
    case $opt in
        --help)
            help
            exit 0
            ;;
        --all)
            sysconf=1
            devtools=1
            dotfiles=1
            ;;
        --sysconf)      sysconf=1   ;;
        --devtools)     devtools=1  ;;
        --dotfiles)     dotfiles=1  ;;
        --vimplugins)   vimplugins=1;;
        *)
            help
            exit 1
            ;;
    esac
done


system_config() {
    if [ `uname` == "Linux" ]; then
        # Enable network time synchronization
        sudo timedatectl set-ntp true
    fi
}


install_dev_tools() {
    if [ -x "$(command -v pacman)" ]; then
        sudo pacman -S --needed zsh vim rustup
    elif [ -x "$(command -v brew)" ]; then
        brew install zsh vim rustup-init
    fi

    if [ -d $HOME/.zplug ]; then
        echo "[Skip] $HOME/.zplug is already exists."
    else
        curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
    fi

    if [ -f $HOME/.vim/autoload/plug.vim ]; then
        echo "[Skip] $HOME/.vim/autoload/plug.vim is already exists."
    else
        curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    fi
}


copy_dotfiles() {
    for dotfile in `ls -A dotfiles | grep -v -e .config -e Library`; do
        cp dotfiles/$dotfile ~
    done

    if [ `uname` == "Darwin" ]; then
        cp -r dotfiles/.config ~
        cp -r dotfiles/Library ~

        for plist in `ls -A dotfiles/Library/Preferences`; do
            defaults import $plist dotfiles/Library/$plist
        done
    else
        mkdir -p ~/.config
        for dir in `ls -A dotfiles/.config | grep -v karabiner`; do
            cp -r dotfiles/.config/$dir ~/.config
        done
    fi
}


if [ $sysconf -eq 1 ]; then
    system_config
fi

if [ $devtools -eq 1 ]; then
    install_dev_tools
fi

if [ $dotfiles -eq 1 ]; then
    copy_dotfiles
fi

if [ $vimplugins -eq 1 ]; then
    vim -c PlugInstall -c qa!
fi

